name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      
      - name: Build Summary
        run: zig build --summary all -freference-trace
      
      - name: Test nanosleep
        run: zig build test_nanosleep -DTests

      - name: Test clock_gettime
        run: zig build test_clock_gettime -DTests
      
      - name: Test clock_getres
        run: zig build test_clock_getres -DTests
